/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database health
         * @description Returns 200 with `db: connected` only if a trivial query round-trips to Postgres. Returns 503 with `db: disconnected` otherwise, in the same shape, so a client can parse either outcome identically.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all securities
         * @description Every ingested security with its price coverage: row count and first and last available date. One aggregate query, so adding tickers does not add round trips. Includes the benchmark index (`^NSEI`), distinguishable by `is_benchmark`.
         */
        get: operations["list_securities_api_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{ticker}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily OHLCV for one security
         * @description Accepts either ticker form (`RELIANCE` or `RELIANCE.NS`). With no date range the most recent 1000 bars are returned, still in ascending date order. Prices are as ingested: the `price_anomalies` overlay is applied when deriving returns, not to these raw bars.
         */
        get: operations["get_prices_api_securities__ticker__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/var": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Monte Carlo VaR / CVaR
         * @description Runs two independent simulations over the same return window and returns them side by side, so any difference between them is the distributional assumption rather than the data.
         *
         *     **Parametric** fits a multivariate normal and draws correlated shocks via a Cholesky factor. **Historical bootstrap** resamples whole historical days, preserving the cross-sectional correlation that actually occurred. Both compound day by day — no sqrt-time scaling.
         *
         *     The response carries a `limitations` array; the parametric method understates tail risk and both estimate correlation from history.
         */
        post: operations["compute_var_api_risk_var_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Markowitz mean-variance optimisation
         * @description Takes a candidate universe — **no weights**, the optimiser determines those — and traces the efficient frontier, returning the minimum-variance and maximum-Sharpe portfolios alongside it.
         *
         *     Every optimisation runs from three starting points and keeps the best converged result. A frontier target the solver cannot reach is skipped and reported in `skipped_target_returns` rather than failing the request.
         *
         *     A `max_weight_per_asset` below `1/len(tickers)` is infeasible and returns 422 with `INFEASIBLE_CONSTRAINTS`.
         */
        post: operations["optimize_api_portfolio_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backtest a strategy against two baselines
         * @description Simulates a constant-mix strategy day by day and runs two baselines over the same calendar: the same holdings bought once and never rebalanced, and the Nifty 50 index.
         *
         *     Share counts are the state, so weights drift naturally between rebalances. Prices are rebuilt from anomaly-corrected returns, so the TMPV demerger and TRENT reset never appear as losses.
         *
         *     **Coverage failures are loud**: every ticker must span the entire requested window or the request returns 422 with `INSUFFICIENT_COVERAGE` naming the ticker and its actual range. The window is never silently shrunk.
         *
         *     The `limitations` array includes the survivorship-bias warning, because this response compares against the index.
         */
        post: operations["run_api_backtest_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrapped distribution of backtest outcomes
         * @description Runs the strategy and both baselines over many paired windows, so the result is a distribution rather than a point estimate.
         *
         *     `rolling_windows` steps a fixed-length window forward one month at a time. `block_bootstrap` resamples blocks of consecutive days (geometric lengths, ~21-day mean) to preserve volatility clustering — resampling individual days would destroy it and produce falsely narrow intervals.
         *
         *     The headline is `win_rates`: how often the strategy beat each baseline, compared window by window. **Read it against the survivorship-bias and price-index warnings in `limitations` before drawing any conclusion.**
         */
        post: operations["bootstrap_api_backtest_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service metadata
         * @description Name, version and where to find the interactive documentation.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRequest
         * @example {
         *       "description": "The response carries a `limitations` array whose first entry is the survivorship-bias warning: the universe is today's index constituents, so the comparison against the Nifty 50 is biased in the strategy's favour.",
         *       "summary": "Monthly rebalanced, 8-year window",
         *       "value": {
         *         "end_date": "2026-09-07",
         *         "initial_capital_inr": 1000000,
         *         "rebalance_frequency": "monthly",
         *         "start_date": "2018-09-10",
         *         "target_weights": {
         *           "HDFCBANK": 0.25,
         *           "ITC": 0.25,
         *           "RELIANCE": 0.25,
         *           "TCS": 0.25
         *         },
         *         "tickers": [
         *           "RELIANCE",
         *           "TCS",
         *           "HDFCBANK",
         *           "ITC"
         *         ],
         *         "transaction_cost_bps": 15
         *       }
         *     }
         */
        BacktestRequest: {
            /** Tickers */
            tickers: string[];
            /** Target Weights */
            target_weights: {
                [key: string]: number;
            };
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Initial Capital Inr
             * @description Starting portfolio value, in INR
             * @default 1000000
             */
            initial_capital_inr: number;
            /**
             * Rebalance Frequency
             * @default monthly
             */
            rebalance_frequency: string;
            /**
             * Transaction Cost Bps
             * @default 15
             */
            transaction_cost_bps: number;
            /**
             * Risk Free Rate
             * @default 0.065
             */
            risk_free_rate: number;
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Tickers */
            tickers: string[];
            /** Target Weights */
            target_weights: {
                [key: string]: number;
            };
            /** @description The trading days the simulation actually ran over */
            data_window: components["schemas"]["DataWindow"];
            /** Initial Capital Inr */
            initial_capital_inr: number;
            /** Rebalance Frequency */
            rebalance_frequency: string;
            /** Transaction Cost Bps */
            transaction_cost_bps: number;
            /** Risk Free Rate */
            risk_free_rate: number;
            strategy: components["schemas"]["BacktestSeries"];
            buy_and_hold_same_stocks: components["schemas"]["BacktestSeries"];
            buy_and_hold_nifty50?: components["schemas"]["BacktestSeries"] | null;
            /** Benchmark Unavailable Reason */
            benchmark_unavailable_reason?: string | null;
            /**
             * Limitations
             * @description Caveats that must be shown alongside these numbers
             */
            limitations?: string[];
        };
        /** BacktestSeries */
        BacktestSeries: {
            /** Label */
            label: string;
            /** Description */
            description: string;
            metrics: components["schemas"]["PerformanceMetrics"];
            /** Values */
            values: components["schemas"]["ValuePoint"][];
        };
        /**
         * BootstrapRequest
         * @example {
         *       "description": "Returns a distribution plus paired win rates. Read `win_rates` only alongside the survivorship-bias and benchmark price-index warnings in `limitations` — a 100% win rate against the index is an artefact of universe selection, not evidence of skill.",
         *       "summary": "Walk-forward, rolling 5-year windows",
         *       "value": {
         *         "include_windows": false,
         *         "method": "rolling_windows",
         *         "rebalance_frequency": "monthly",
         *         "seed": 0,
         *         "strategy": {
         *           "kind": "walk_forward",
         *           "lookback_days": 504,
         *           "max_weight_per_asset": 0.35,
         *           "objective": "max_sharpe"
         *         },
         *         "tickers": [
         *           "RELIANCE",
         *           "TCS",
         *           "HDFCBANK",
         *           "INFY",
         *           "ITC",
         *           "SUNPHARMA",
         *           "MARUTI",
         *           "NTPC"
         *         ],
         *         "window_years": 5
         *       }
         *     }
         */
        BootstrapRequest: {
            /** Tickers */
            tickers: string[];
            strategy?: components["schemas"]["StrategySpec"];
            /**
             * Window Years
             * @description Length of each window (max 20 years)
             * @default 5
             */
            window_years: number;
            /**
             * Method
             * @default rolling_windows
             * @enum {string}
             */
            method: "rolling_windows" | "block_bootstrap";
            /**
             * Initial Capital Inr
             * @description Starting portfolio value, in INR
             * @default 1000000
             */
            initial_capital_inr: number;
            /**
             * Rebalance Frequency
             * @default monthly
             * @enum {string}
             */
            rebalance_frequency: "monthly" | "quarterly";
            /**
             * Transaction Cost Bps
             * @default 15
             */
            transaction_cost_bps: number;
            /**
             * Risk Free Rate
             * @default 0.065
             */
            risk_free_rate: number;
            /**
             * N Resamples
             * @description Block-bootstrap resamples (max 1,000)
             * @default 200
             */
            n_resamples: number;
            /**
             * Expected Block Days
             * @default 21
             */
            expected_block_days: number;
            /**
             * Seed
             * @default 0
             */
            seed: number | null;
            /**
             * Include Windows
             * @description Include the per-window array for charting
             * @default true
             */
            include_windows: boolean;
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /** Method */
            method: string;
            /** Strategy Kind */
            strategy_kind: string;
            /** Tickers */
            tickers: string[];
            /** @description The full span of data the windows or resamples were drawn from */
            data_window: components["schemas"]["DataWindow"];
            /** Window Years */
            window_years: number;
            /** N Windows */
            n_windows: number;
            /** Rebalance Frequency */
            rebalance_frequency: string;
            /** Transaction Cost Bps */
            transaction_cost_bps: number;
            /** Risk Free Rate */
            risk_free_rate: number;
            win_rates: components["schemas"]["WinRatesOut"];
            /** Summaries */
            summaries: {
                [key: string]: {
                    [key: string]: components["schemas"]["MetricSummaryOut"];
                };
            };
            /** Total Rebalances */
            total_rebalances: number;
            /** Total Optimizer Failures */
            total_optimizer_failures: number;
            /** Average Turnover Per Rebalance */
            average_turnover_per_rebalance: number;
            /** Skipped Windows */
            skipped_windows?: string[];
            /** Windows */
            windows?: components["schemas"]["WindowResultOut"][];
            /**
             * Limitations
             * @description Caveats that must be shown alongside these numbers
             */
            limitations?: string[];
        };
        /**
         * DataWindow
         * @description The data that actually backed a result.
         *
         *     ``start_date``, ``end_date`` and ``trading_days`` are always present. The
         *     remaining fields describe *lookback shrinking*, which applies to the
         *     estimation endpoints (VaR, optimiser) and is null for the backtester —
         *     that one refuses to shrink and fails instead, so there is nothing to report.
         */
        DataWindow: {
            /**
             * Start Date
             * Format: date
             * @description First trading day actually used
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Last trading day actually used
             */
            end_date: string;
            /**
             * Trading Days
             * @description Number of trading days in the window
             */
            trading_days: number;
            /**
             * Requested Lookback Days
             * @description Window length asked for, where applicable
             */
            requested_lookback_days?: number | null;
            /**
             * Shrunk
             * @description True when the window is shorter than requested because a ticker's history did not reach back far enough
             * @default false
             */
            shrunk: boolean;
            /**
             * Constrained By
             * @description Ticker whose history bound the window
             */
            constrained_by?: string | null;
            /**
             * Constraint Reason
             * @description Prose explanation of the constraint
             */
            constraint_reason?: string | null;
            /**
             * First Available Date By Ticker
             * @description True start of each ticker's price history
             */
            first_available_date_by_ticker?: {
                [key: string]: string;
            };
        };
        /**
         * ErrorResponse
         * @description The only error shape this API returns.
         */
        ErrorResponse: {
            /**
             * Error Code
             * @description Stable machine-readable code; safe to branch on
             * @example INSUFFICIENT_COVERAGE
             */
            error_code: string;
            /**
             * Message
             * @description Human-readable and actionable: names the offending value
             * @example JIOFIN has data from 2023-08-21 to 2026-09-07, which does not cover the requested 2022-01-03 to 2026-06-30
             */
            message: string;
            /**
             * Details
             * @description Structured context — field paths, offending tickers, limits
             */
            details?: Record<string, never>;
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @description "ok" when the database round-trips
             */
            status: string;
            /**
             * Db
             * @description "connected" or "disconnected"
             */
            db: string;
        };
        /**
         * MethodResult
         * @description One simulation method's output.
         */
        MethodResult: {
            /** Method */
            method: string;
            /** Description */
            description: string;
            /** Estimates */
            estimates: components["schemas"]["VarEstimate"][];
            /** Mean Horizon Return Pct */
            mean_horizon_return_pct: number;
            /** Worst Simulated Pnl Inr */
            worst_simulated_pnl_inr: number;
            /** Best Simulated Pnl Inr */
            best_simulated_pnl_inr: number;
        };
        /** MetricSummaryOut */
        MetricSummaryOut: {
            /** Median */
            median: number;
            /** P5 */
            p5: number;
            /** P95 */
            p95: number;
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** N Windows */
            n_windows: number;
        };
        /**
         * OptimizeRequest
         * @example {
         *       "lookback_days": 504,
         *       "max_weight_per_asset": 0.35,
         *       "n_frontier_points": 30,
         *       "risk_free_rate": 0.065,
         *       "seed": 0,
         *       "tickers": [
         *         "RELIANCE",
         *         "TCS",
         *         "HDFCBANK",
         *         "INFY",
         *         "ITC",
         *         "SUNPHARMA",
         *         "MARUTI",
         *         "NTPC"
         *       ]
         *     }
         */
        OptimizeRequest: {
            /**
             * Tickers
             * @description Candidate universe; the optimiser determines the weights
             */
            tickers: string[];
            /**
             * Risk Free Rate
             * @description Annualised, as a fraction. Default ~short-tenor Indian rate.
             * @default 0.065
             */
            risk_free_rate: number;
            /**
             * Max Weight Per Asset
             * @default 0.35
             */
            max_weight_per_asset: number;
            /**
             * Allow Short
             * @description Permit negative weights, bounded by -max_weight_per_asset
             * @default false
             */
            allow_short: boolean;
            /**
             * Lookback Days
             * @description Estimation window in trading days (max 2,520)
             * @default 504
             */
            lookback_days: number;
            /**
             * N Frontier Points
             * @description Points to trace along the frontier (max 200)
             * @default 30
             */
            n_frontier_points: number;
            /**
             * Seed
             * @description Seeds the optimiser's random restarts
             * @default 0
             */
            seed: number | null;
        };
        /** OptimizeResponse */
        OptimizeResponse: {
            /** Tickers */
            tickers: string[];
            /** Risk Free Rate */
            risk_free_rate: number;
            /** Max Weight Per Asset */
            max_weight_per_asset: number;
            /** Allow Short */
            allow_short: boolean;
            data_window: components["schemas"]["DataWindow"];
            /** Efficient Frontier */
            efficient_frontier: components["schemas"]["OptimizedPortfolio"][];
            min_variance_portfolio: components["schemas"]["OptimizedPortfolio"];
            max_sharpe_portfolio: components["schemas"]["OptimizedPortfolio"];
            /** Frontier Points Requested */
            frontier_points_requested: number;
            /** Frontier Points Returned */
            frontier_points_returned: number;
            /**
             * Skipped Target Returns
             * @description Target returns the solver could not reach; these were skipped so the rest of the frontier could still be returned
             */
            skipped_target_returns?: number[];
            /**
             * Limitations
             * @description Caveats that must be shown alongside these numbers
             */
            limitations?: string[];
        };
        /**
         * OptimizedPortfolio
         * @description One point on (or in) the frontier.
         */
        OptimizedPortfolio: {
            /**
             * Expected Return
             * @description Annualised, as a fraction (0.14 = 14%)
             */
            expected_return: number;
            /**
             * Volatility
             * @description Annualised standard deviation
             */
            volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /** PerformanceMetrics */
        PerformanceMetrics: {
            /** Cagr */
            cagr: number;
            /**
             * Annualised Return
             * @description Arithmetic mean daily return x 252; matches the optimiser's convention so Sharpe ratios are comparable across endpoints
             */
            annualised_return: number;
            /** Annualised Volatility */
            annualised_volatility: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Sortino Ratio */
            sortino_ratio: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Max Drawdown Peak Date */
            max_drawdown_peak_date: string | null;
            /** Max Drawdown Trough Date */
            max_drawdown_trough_date: string | null;
            /** Total Transaction Costs Inr */
            total_transaction_costs_inr: number;
            /** Total Transaction Costs Pct */
            total_transaction_costs_pct: number;
            /**
             * N Rebalances
             * @description Rebalance events executed, including the day-one purchase
             */
            n_rebalances: number;
            /** Start Value Inr */
            start_value_inr: number;
            /** End Value Inr */
            end_value_inr: number;
            /** Total Return */
            total_return: number;
        };
        /**
         * Portfolio
         * @description A set of positions and the rupee value they represent.
         *
         *     Weights must sum to 1.0. Negative weights are permitted so the same schema
         *     can carry a short book later; the sum constraint still applies.
         */
        Portfolio: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            /**
             * Total Value Inr
             * @description Total portfolio value, in INR
             */
            total_value_inr: number;
        };
        /**
         * Position
         * @description One holding: a ticker and its share of the portfolio.
         */
        Position: {
            /**
             * Ticker
             * @description NSE symbol; the '.NS' suffix is accepted and stripped
             */
            ticker: string;
            /**
             * Weight
             * @description Share of total_value, as a fraction (0.25 = 25%)
             */
            weight: number;
        };
        /** PriceBar */
        PriceBar: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Adj Close */
            adj_close: number | null;
            /** Volume */
            volume: number | null;
        };
        /** PriceSeries */
        PriceSeries: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Count */
            count: number;
            /** First Date */
            first_date: string | null;
            /** Last Date */
            last_date: string | null;
            /** Capped */
            capped: boolean;
            /** Limit */
            limit: number | null;
            /** Prices */
            prices: components["schemas"]["PriceBar"][];
        };
        /** SecuritySummary */
        SecuritySummary: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Exchange */
            exchange: string;
            /** Sector */
            sector: string | null;
            /** Is Active */
            is_active: boolean;
            /** Row Count */
            row_count: number;
            /** First Date */
            first_date: string | null;
            /** Last Date */
            last_date: string | null;
        };
        /** ServiceInfo */
        ServiceInfo: {
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Docs
             * @description Path to the interactive API documentation
             */
            docs: string;
        };
        /** StrategySpec */
        StrategySpec: {
            /**
             * Kind
             * @default constant_mix
             * @enum {string}
             */
            kind: "constant_mix" | "walk_forward";
            /**
             * Target Weights
             * @description Required for constant_mix; ignored otherwise
             */
            target_weights?: {
                [key: string]: number;
            } | null;
            /**
             * Lookback Days
             * @default 504
             */
            lookback_days: number;
            /**
             * Max Weight Per Asset
             * @default 0.35
             */
            max_weight_per_asset: number;
            /**
             * Objective
             * @default max_sharpe
             * @enum {string}
             */
            objective: "max_sharpe" | "min_variance";
            /**
             * Allow Short
             * @default false
             */
            allow_short: boolean;
        };
        /** ValuePoint */
        ValuePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Value Inr
             * @description Portfolio value on this date, in INR
             */
            value_inr: number;
        };
        /**
         * VarEstimate
         * @description VaR and CVaR at one confidence level, in rupees and as a percentage.
         */
        VarEstimate: {
            /** Confidence Level */
            confidence_level: number;
            /**
             * Var Inr
             * @description Loss not expected to be exceeded, in INR
             */
            var_inr: number;
            /**
             * Var Pct
             * @description Same loss as a percentage of total_value
             */
            var_pct: number;
            /**
             * Cvar Inr
             * @description Mean loss in the tail beyond VaR, in INR
             */
            cvar_inr: number;
            /** Cvar Pct */
            cvar_pct: number;
        };
        /**
         * VarRequest
         * @example {
         *       "confidence_levels": [
         *         0.95,
         *         0.99
         *       ],
         *       "horizon_days": 10,
         *       "lookback_days": 504,
         *       "n_sims": 10000,
         *       "portfolio": {
         *         "positions": [
         *           {
         *             "ticker": "RELIANCE",
         *             "weight": 0.4
         *           },
         *           {
         *             "ticker": "TCS",
         *             "weight": 0.3
         *           },
         *           {
         *             "ticker": "HDFCBANK",
         *             "weight": 0.3
         *           }
         *         ],
         *         "total_value_inr": 1000000
         *       },
         *       "seed": 42
         *     }
         */
        VarRequest: {
            portfolio: components["schemas"]["Portfolio"];
            /**
             * N Sims
             * @description Simulation paths (max 200,000)
             * @default 10000
             */
            n_sims: number;
            /**
             * Horizon Days
             * @description Trading days to simulate forward (max 252)
             * @default 1
             */
            horizon_days: number;
            /**
             * Confidence Levels
             * @default [
             *       0.95,
             *       0.99
             *     ]
             */
            confidence_levels: number[];
            /**
             * Lookback Days
             * @description Estimation window in trading days (max 2,520)
             * @default 504
             */
            lookback_days: number;
            /**
             * Seed
             * @description Set for reproducible simulations
             */
            seed?: number | null;
        };
        /**
         * VarResponse
         * @description Both methods side by side, plus the context needed to read them.
         */
        VarResponse: {
            /**
             * Total Value Inr
             * @description Portfolio value the P&L figures are denominated against
             */
            total_value_inr: number;
            /** Tickers */
            tickers: string[];
            /** Weights */
            weights: {
                [key: string]: number;
            };
            /** N Sims */
            n_sims: number;
            /** Horizon Days */
            horizon_days: number;
            /** Confidence Levels */
            confidence_levels: number[];
            /** Seed */
            seed: number | null;
            data_window: components["schemas"]["DataWindow"];
            parametric: components["schemas"]["MethodResult"];
            historical_bootstrap: components["schemas"]["MethodResult"];
            /**
             * Limitations
             * @description Caveats that must be shown alongside these numbers
             */
            limitations?: string[];
        };
        /**
         * WinRatesOut
         * @description Paired, window by window — the headline number for this endpoint.
         */
        WinRatesOut: {
            /**
             * Vs Nifty50 Cagr
             * @description Fraction of windows where the strategy's CAGR beat the index
             */
            vs_nifty50_cagr: number;
            /**
             * Vs Nifty50 Sharpe
             * @description Fraction of windows where the strategy's Sharpe beat the index
             */
            vs_nifty50_sharpe: number;
            /** Vs Buy And Hold Cagr */
            vs_buy_and_hold_cagr: number;
            /** Vs Buy And Hold Sharpe */
            vs_buy_and_hold_sharpe: number;
            /** N Windows */
            n_windows: number;
        };
        /** WindowMetricsOut */
        WindowMetricsOut: {
            /** Cagr */
            cagr: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Sortino Ratio */
            sortino_ratio: number;
            /** Max Drawdown */
            max_drawdown: number;
        };
        /** WindowResultOut */
        WindowResultOut: {
            /** Index */
            index: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Trading Days */
            trading_days: number;
            /** N Rebalances */
            n_rebalances: number;
            /** N Optimizer Failures */
            n_optimizer_failures: number;
            /** Average Turnover */
            average_turnover: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["WindowMetricsOut"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    list_securities_api_securities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Securities ordered by ticker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecuritySummary"][];
                };
            };
        };
    };
    get_prices_api_securities__ticker__prices_get: {
        parameters: {
            query?: {
                /** @description Inclusive start date (YYYY-MM-DD) */
                start?: string | null;
                /** @description Inclusive end date (YYYY-MM-DD) */
                end?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeries"];
                };
            };
            /** @description Ticker not in the database */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid date range */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compute_var_api_risk_var_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VarRequest"];
            };
        };
        responses: {
            /** @description Both methods, the data window used, and the caveats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VarResponse"];
                };
            };
            /** @description Request cannot be satisfied — see `error_code` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optimize_api_portfolio_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description The frontier, its two named portfolios, and the caveats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizeResponse"];
                };
            };
            /** @description Request cannot be satisfied — see `error_code` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_api_backtest_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Strategy, both baselines, their metrics, and the caveats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Request cannot be satisfied — see `error_code` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bootstrap_api_backtest_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Percentile summaries, paired win rates, and the caveats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Request cannot be satisfied — see `error_code` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfo"];
                };
            };
        };
    };
}
