"""add price_anomalies overlay table

Revision ID: 11a6f5ed1ffc
Revises: adfc66012b35
Create Date: 2026-09-07 11:32:01.635432

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '11a6f5ed1ffc'
down_revision: str | None = 'adfc66012b35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adjustment', sa.Enum('exclude_return', name='anomaly_adjustment'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'date', name='uq_price_anomalies_security_id_date')
    )
    op.create_index(op.f('ix_price_anomalies_date'), 'price_anomalies', ['date'], unique=False)
    op.create_index(op.f('ix_price_anomalies_security_id'), 'price_anomalies', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_anomalies_security_id'), table_name='price_anomalies')
    op.drop_index(op.f('ix_price_anomalies_date'), table_name='price_anomalies')
    op.drop_table('price_anomalies')
    # Autogenerate creates the enum type but never drops it; without this a
    # downgrade followed by an upgrade fails with "type already exists".
    sa.Enum(name='anomaly_adjustment').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
